name: Coding Conventions

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-style:
    name: Run Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer --allow-risky=yes --dry-run -v
        env:
          PHP_CS_FIXER_IGNORE_ENV: true

  phpstan:
    name: "Run Static Analysis: PHPStan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        run: vendor/bin/phpstan --error-format=github

  rector:
    name: "Run Static Analysis: Rector"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Rector
        run: vendor/bin/rector process --no-ansi --dry-run --no-progress-bar
