name: Isolated Tests

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  get_packages:
    name: Get Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get Packages
        id: get_json
        run: echo "json=$(bin/get-packages)" >> $GITHUB_OUTPUT

      - name: Output Packages
        run: echo "${{ steps.get_json.outputs.json }}"
    outputs:
      matrix: ${{ steps.get_json.outputs.json }}

  phpunit:
    runs-on: ${{ matrix.os }}
    needs: get_packages
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        package: ${{ fromJson(needs.get_packages.outputs.matrix) }}
        php:
          - 8.3
        stability:
          - prefer-stable
          - prefer-lowest

    name: "Run Tests: ${{ matrix.package.name }} - PHP ${{ matrix.php }} - ${{ matrix.stability }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, pcntl, fileinfo
          tools: phpunit
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          ./bin/build-changed-packages
          cd "src/Tempest/${{ matrix.package.basename }}"
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: phpunit -c "src/Tempest/${{ matrix.package.basename }}/phpunit.xml" --coverage-clover build/reports/clover.xml

      # Only upload coverage once
      - if: matrix.php == '8.3' && matrix.os == 'ubuntu-latest' && matrix.stability == 'prefer-stable'
        name: Upload coverage results to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: build/reports/clover.xml
          flag-name: "Unit-${{ matrix.package.name }}"

  finish:
    needs:
      - get_packages
      - phpunit
    runs-on: ubuntu-latest
    steps:
      - name: Get Package Flags
        id: get-package-flags
        run: |
          packages=$(echo '${{ needs.get_packages.outputs.matrix }}' | jq -r '.[].name')

          # Prepend "Unit-" to each .name value and join with commas
          result=$(for package in $packages; do echo -n "Unit-$package,"; done | sed 's/,$//')

          echo "Result: $result"
          
          echo "packages=$result" >> $GITHUB_OUTPUT
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: ${{ steps.get-package-flags.outputs.packages }}